const projects = [
  {
    id: "mockly",
    appId: "project-mockly",
    title: "Mockly",
    domain: "Natural Language Processing",
    description: "AI Mock Interview Platform",
    url: "NA",
    github: "https://github.com/Lokesh-Kudipudi/Mockly",
    images: [
      "/projects/mockly/1-home.png",
      "/projects/mockly/2-interview-call.png",
      "/projects/mockly/3-dashboard.png",
      "/projects/mockly/4-aboutme.png",
      "/projects/mockly/5-interview-details.png",
    ],
    readme: [
      "Engineered a real-time voice interview platform (React + Flask + Socket.IO; Whisper ASR + Gemini + Kokoro TTS) and cut end-to-end time-to-first-audio by 77% (6.6 s → 1.5 s, p95 6.7 s → 1.4 s) by pipelining streaming Gemini token output through a sentence-buffered TTS consumer over a producer/consumer queue; instrumented a per-stage latency pipeline (VAD / ASR / LLM / TTS) with a context-manager telemetry primitive, persisting p50/p95 timings to MongoDB and surfacing them in a session-level dashboard that isolated LLM + TTS as ~85% of turn latency.",
      "Built a browser-side AudioWorklet capture pipeline with RMS-based automatic barge-in (4-frame threshold, 1.2 s cooldown) that interrupts AI playback within one audio frame and drains the server-side TTS stream via a threading.Event cancel signal — enabling natural mid-sentence interruption without dropped audio or stale playback buffers.",
      "Designed an on-demand interview-scoring service backed by Gemini with a Pydantic-typed response schema (overall + four per-dimension scores, strengths / weaknesses / suggestions), with insufficient-evidence short-circuiting and output sanitization to guard model spend and schema stability; secured the platform with Argon2 + JWT in httpOnly SameSite cookies shared across REST and Socket.IO with a @require_user decorator scoping every resource by user_id; and implemented a self-correcting interviewer that extracts asked questions post-interview and re-injects the last five sessions' questions into the next system prompt as a do-not-repeat block.",
    ],
    skills: ["ReactJS", "Flask", "Google-GenAI", "Faster-Whisper", "Salero-VAD", "Kokoro TTS", "TypeScript"],
    window: { width: 860, height: 620 },
    
  },
  {
    id: "book-translator",
    appId: "project-book-translator",
    title: "Book Translator",
    domain: "Natural Language Processing",
    description: "Book Translator Application",
    url: "https://colab.research.google.com/drive/1Heo4jzo0PnGBksxlaMT9sWVyoGOJSuzo?usp=sharing",
    github: "https://github.com/Lokesh-Kudipudi/Book-Translator",
    images: [
      "/projects/book-translator/1-bt.png",
      "/projects/book-translator/2-bt.png",
      "/projects/book-translator/3-bt.png",
      "/projects/book-translator/4-bt.png",
    ],
    readme: [
      "Built a document translation pipeline using IndicTrans2 to translate English PDFs/TXTs into 25+ Indic languages, integrating PyMuPDF-based layout preservation logic to extract text coordinates and reconstruct translated documents with original font, color, and alignment intact.",
      "Optimized IndicTrans2 inference via 4-bit and 8-bit quantization, reducing VRAM requirements by ~70% while maintaining translation accuracy; validated model performance quantitatively using BLEU, METEOR, and TER metrics benchmarked against Google Translate and Gemini.",
      "Architected a Gradio-based web interface featuring real-time side-by-side previews of original and translated documents, delivering an end-to-end user-facing system from raw document upload through language-accurate, layout-preserved output.",
    ],
    skills: ["PyMuPDF", "Gradio", "IndicTrans2", "Hugging Face Transformers", "BitsAndBytes"],
    window: { width: 860, height: 620 },
  },
  {
    id: "devquiz",
    appId: "project-devquiz",
    title: "DevQuiz",
    domain: "Web Development",
    description: "A Platform for Aptitude, Coding rounds preparation",
    url: "https://dev-quiz-nine.vercel.app/",
    github: "https://github.com/Lokesh-Kudipudi/DevQuiz",
    images: [
      "/projects/devquiz/1-dashboard.png",
      "/projects/devquiz/2-group-dashboard.png",
      "/projects/devquiz/3-quiz.png",
      "/projects/devquiz/4-quiz-leaderboard.png",
      "/projects/devquiz/5-quiz-results.png",
      "/projects/devquiz/6-personal-dashboard.png",
    ],
    readme: [
      "Built a full-stack assessment platform with 2 product modes (group + solo), 3 assessment formats (Quiz, Coding Round, Online Assessment), and 15+ React screens using React, Express, and MongoDB.",
      "Implemented secure auth with 3 login paths (Google OAuth, email/password, demo), JWT + HTTP-only cookies, and protected routing to enforce access control across creator/member/participant flows.",
      "Engineered real-time competitive workflows using Socket.IO for coding rounds (lobby/live/results) and delivered persistent analytics with a UTC streak engine aggregating activity across 3 learning surfaces (quiz, OA, coding).",
    ],
    skills: ["ReactJS", "TailwindCSS", "ExpressJS", "MongoDB", "Socket.IO", "Google OAuth 2.0", "Gemini API"],
    window: { width: 860, height: 620 },
  },
  {
    id: "chasing-horizons",
    appId: "project-chasing-horizons",
    title: "Chasing Horizons",
    domain: "Web Development",
    description: "A Comprehensive Tours and Hotels Booking Platform",
    url: "https://chasing-horizon.vercel.app/",
    github: "https://github.com/Lokesh-Kudipudi/Chasing_Horizons_M2025_S2026",
    images: [
      "/projects/chasing-horizons/chasing-horizon-1.png",
      "/projects/chasing-horizons/chasing-horizon-2.png",
      "/projects/chasing-horizons/chasing-horizon-3.png",
      "/projects/chasing-horizons/chasing-horizon-4.png",
    ],
    readme: [
      "Built a full-stack travel platform (React 19, Node/Express, MongoDB) and improved core listing performance between benchmark runs: getAllTours from 313ms to 120ms (62% faster), getTopDestinations from 198ms to 95ms (52% faster), and getAllHotels from 111ms to 34ms (~69% faster).",
      "Implemented cache-backed analytics endpoints that cut average response time from ~252ms (cache miss) to ~50ms (cache hit) across 6 admin APIs (~80% latency reduction).",
      "Engineered a production-ready API layer (13+ route groups, 18+ controllers) with JWT/cookie auth, rate limiting, security middleware, and Dockerized frontend/backend deployment, enabling multi-role workflows at scale for travelers, admins, hotel managers, tour guides, owners, and employees.",
    ],
    skills: ["ReactJS", "ExpressJS", "MongoDB", "Redis", "Coudinary", "Gemini API"],
    window: { width: 860, height: 620 },
  },
  {
    id: "railway-sleeper-crack-detection",
    appId: "project-railway-sleeper-crack-detection",
    title: "Railway Sleeper Crack Detection",
    domain: "Computer Vision",
    description: "Detection of cracks on railway sleepers",
    url: "NA",
    github: "NA",
    images: [],
    readme: [
        "Manually annotated 421 crack instances and 100+ sleeper/rail segmentation masks across a real-world dataset of 444 high-resolution images (avg. 4032×3024 px), covering varied lighting, track conditions, and crack types to address the lab-only dataset gap present in prior literature.",
        "Engineered a two-stage inference pipeline — first segmenting sleeper regions using a YOLOv8n-seg model (mAP50: 94.9%, mask precision: 97.2%), then tiling each ROI into 1024×1024 patches for crack detection — improving mAP50 by 286%, mAP50-95 by 574%, and precision by 199% over the direct downscaling baseline.",
        "Diagnosed severe train-validation overfitting (~45% gap) across nano-scale YOLO models trained on a limited 108-image dataset and reduced it to ~17% by applying heavy augmentation strategies including mosaic, copy-paste, and increased weight decay, while maintaining validation accuracy — establishing a reproducible regularization recipe for small-dataset crack detection tasks.",
    ],
    skills: ["Yolo", "OpenCV", "Matplotlib", "wandb"],
    window: { width: 860, height: 620 },
  },
  {
    id: "no-proxy",
    appId: "project-no-proxy",
    title: "No Proxy",
    domain: "Mobile App Development",
    description: "Attendance tracker application",
    url: "NA",
    github: "https://github.com/Lokesh-Kudipudi/IIITS-Attendence",
    images: [
        "/projects/no-proxy/1-sign-in.png",
        "/projects/no-proxy/2-sign-up.png",
        "/projects/no-proxy/3-student-dashboard.png",
        "/projects/no-proxy/4-teacher-dashboard.png",
        "/projects/no-proxy/5-teacher-attendence.png",
        "/projects/no-proxy/6-student-attendence.png",
        "/projects/no-proxy/7-classroom.png",
        "/projects/no-proxy/8-class-settings.png",
        "/projects/no-proxy/9-profile.png",
    ],
    readme: [
        "Node.js/Express + MongoDB backend with a React Native (Expo) mobile frontend, supporting both Classroom and Office environments.",
        "Owner, Admin, Office Manager, Teacher, Employee, and Student, each with tailored workflows for marking, tracking, and analyzing attendance.",
        "OTP authentication combined with geofencing/GPS, IP-based checks, and biometric verification to ensure accurate, tamper-resistant attendance records.",
    ],
    skills: ["React Native", "TypeScript", "MongoDB", "NodeJS", "ExpressJS"],
    window: { width: 860, height: 620 },
  },
  {
    id: "dispatch",
    appId: "project-dispatch",
    title: "Dispatch",
    domain: "Agentic AI and MLOps",
    description: "HR Outreach agent",
    url: "NA",
    github: "https://dagshub.com/Lokesh-Kudipudi/Dispatch",
    images: [
        "/projects/dispatch/1-runs.png",
        "/projects/dispatch/2-posts.png",
        "/projects/dispatch/3-contacts.png",
        "/projects/dispatch/4-links.png",
        "/projects/dispatch/5-drafts.png",
        "/projects/dispatch/6-resume.png",
        "/projects/dispatch/7-settings.png",
    ],
    readme: [
        "Built an end‑to‑end HR outreach agent that scrapes LinkedIn #hiring posts using a persistent Playwright profile, normalizes contacts and links, and uses a LangGraph + Gemini pipeline to generate personalized email drafts, with a hard approval gate before pushing to Gmail.",
        "Delivered the full stack and MLOps backbone: FastAPI + async SQLAlchemy/Alembic backend, React/TypeScript frontend with typed API contracts, and MLflow on DagsHub plus DVC dataset versioning to track precision/labeling metrics and reproduce evaluations by commit.",
    ],
    skills: ["LangGraph", "FastAPI", "MLFlow", "DVC", "AirFlow", "Grafana", "Prometheus"],
    window: { width: 860, height: 620 },
  }
];

export default projects;
